project_id = "zsljoigcvvbzmsjmpugp"

[functions.create-share]
verify_jwt = false

[functions.get-share]
verify_jwt = false

[functions.setup-2fa]
verify_jwt = true

[functions.verify-2fa]
verify_jwt = true

[functions.disable-2fa]
verify_jwt = true